use_frameworks!

platform :ios, '10.0'

target 'ZDMediator_Example' do
  #pod 'ZDMediator', :path => '../', :subspecs => ['Core', 'DisableAssert']
  pod 'ZDMediator', :path => '../'

  target 'ZDMediator_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
