use_frameworks!

platform :ios, '13.0'

target 'ZDMediator_Example' do
  pod 'ZDMediator', :path => '../'

  target 'ZDMediator_Tests' do
    inherit! :complete

    #pod 'FBSnapshotTestCase'
  end
end
